#include <iostream>
#include <exception>

// untuk obyek exception yang akan digunakan
#include <array>
// untuk array exception yang akan digunakan
using namespace std;

int main() 
{
    cout << "Awal Program" << endl; // penanda 1:....
    try
    {
       array<int, 3> data = { 10, 20, 30 };
       // pesan array integer 3 elemen
      
    }
    catch (exception& e)
    {
        
    }

   
}